# Generated by Django 4.2.5 on 2023-10-27 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='nombre',
            field=models.CharField(default='juanito', max_length=200),
        ),
    ]
