# Generated by Django 3.1.3 on 2023-11-25 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('especie', models.CharField(max_length=200)),
                ('raza', models.CharField(max_length=200)),
                ('edad', models.IntegerField()),
                ('nombre_dueño', models.CharField(max_length=200)),
                ('run_dueño', models.CharField(max_length=200)),
            ],
        ),
    ]
