# Generated by Django 3.1.3 on 2023-11-25 22:52

import citas.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
        ('usuarios', '0003_auto_20231125_2225'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita_con_medico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField(default=datetime.date.today, help_text='Introduzca una fecha para la cita', validators=[citas.models.validar_dia])),
                ('horario', models.CharField(choices=[('1', '07:00 AM a 08:00 AM'), ('2', '08:00 AM a 09:00 AM'), ('3', '09:00 AM a 10:00 AM'), ('4', '10:00 AM a 11:00 AM'), ('5', '11:00 AM a 12:00 PM')], default=datetime.date.today, max_length=10)),
                ('Mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Mascota_medicos', to='pacientes.mascota')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Horas_medicos', to='usuarios.medico')),
            ],
            options={
                'unique_together': {('horario', 'dia')},
            },
        ),
    ]
