# Generated by Django 4.2.5 on 2023-10-18 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cita_con_medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Paciente', models.CharField(max_length=255)),
                ('Nombre_doctor', models.CharField(max_length=255)),
                ('Fecha_hora', models.DateTimeField()),
            ],
        ),
    ]
