# Generated by Django 4.2.5 on 2023-10-28 05:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_cita_con_medico_dia_cita_con_medico_horario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita_con_medico',
            name='horario',
            field=models.CharField(choices=[('1', '07:00 AM a 08:00 AM'), ('2', '08:00 AM a 09:00 AM'), ('3', '09:00 AM a 10:00 AM'), ('4', '10:00 AM a 11:00 AM'), ('5', '11:00 AM a 12:00 PM')], default=datetime.date.today, max_length=10),
        ),
    ]
