# Generated by Django 4.2.5 on 2023-11-24 03:02

import citas.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_medico_nombre_diferentesuser_medico_usuario'),
        ('pacientes', '0001_initial'),
        ('citas', '0002_cita_con_medico_dia_cita_con_medico_horario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita_con_medico',
            name='Paciente',
        ),
        migrations.AlterField(
            model_name='cita_con_medico',
            name='dia',
            field=models.DateField(help_text='Introduzca una fecha para la cita', validators=[citas.models.validar_dia]),
        ),
        migrations.AlterField(
            model_name='cita_con_medico',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas_medico', to='usuarios.medico'),
        ),
        migrations.CreateModel(
            name='HorarioVeterinario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('ocupado', models.BooleanField(default=False)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.medico')),
            ],
        ),
        migrations.AddField(
            model_name='cita_con_medico',
            name='paciente',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='citas_paciente', to='pacientes.pacientes'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cita_con_medico',
            name='horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='citas.horarioveterinario'),
        ),
    ]
