# Generated by Django 4.2.5 on 2023-10-28 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0004_alter_cita_con_medico_paciente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita_con_medico',
            name='Paciente',
            field=models.CharField(max_length=250),
        ),
    ]
