# Generated by Django 4.2.5 on 2023-10-28 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
        ('citas', '0005_alter_cita_con_medico_paciente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita_con_medico',
            name='Paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Pacientes_medicos', to='pacientes.pacientes'),
        ),
    ]
